# Generated by Django 3.1.1 on 2020-09-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_projectimage_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='upload',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
