# Generated by Django 3.1.1 on 2020-09-16 19:33

from django.db import migrations, models
import markdownx.models


def add_homepage(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Snippet = apps.get_model("frontend", "Snippet")
    Snippet.objects.create(
        slug="homepage", text="# Kim Strudwick\n\nWorking with photography and film"
    )
    Snippet.objects.create(
        slug="about", text="Film and photography artist working in Stroud"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0003_projectimage_upload"),
    ]

    operations = [
        migrations.CreateModel(
            name="Snippet",
            fields=[
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                ("text", markdownx.models.MarkdownxField()),
            ],
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="description",
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="upload",
            field=models.ImageField(upload_to="project_images"),
        ),
        migrations.RunPython(add_homepage),
    ]
