# Generated by Django 3.1.1 on 2020-09-30 14:55

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20200916_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date']},
        ),
        migrations.CreateModel(
            name='ProjectVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', markdownx.models.MarkdownxField(blank=True)),
                ('vimeo_id', models.CharField(max_length=30)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='frontend.project')),
            ],
        ),
    ]
