name: CMS runner
on:
  workflow_dispatch:
    inputs:
      heroku_domain:
        description: 'Heroku domain to grab'
        required: true
        default: 'fast-gorge-49964.herokuapp.com'

jobs:
  cms:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Wget from Heroku
        run: |
          wget --no-host-directories --directory-prefix=. --mirror --convert-links --html-extension ${{ github.event.inputs.heroku_domain }}
      - name: Commit back to repo
        uses: EndBug/add-and-commit@v4
